### ISSUE TITLE
Whisk doesn't accept project jsonte array

### ISSUE THREAD

**Issue by bogumidu** [MCDevKit/regolith-library#4]
While processing project with whisk if dependency uses jsonte array it doesn't allow to redefine used array

Given:
  Project A that uses Project B as whisk filter
  Project B uses jsonte templating with array 'jsonteArray'
  Project A defines 'jsonteArray'
  
Expected:
  Whisked in Project B uses 'jsonteArray' defined in Project A files

Actual:
  Whisked in Project B cannot process 'jsonteArray' into array

Commandline Error:
```sh
[INFO]  [jsonte:subfilter3] [ERROR]     An error occurred while processing the template file BP\animation_controllers\templated_file.ac.templ
[INFO]  [jsonte:subfilter3] [+]: Iteration action must evaluate to an array at $template/animation_controllers
New version available!
https://github.com/Bedrock-OSS/regolith/releases/tag/1.1.0
[ERROR] Failed to run profile "default"
[+]: Failed to run filter.
  >> Filter: jsonte
[+]: Failed to run filter.
  >> Filter: the 4th subfilter of "jsonte" filter
[+]: Failed to run exe file.
  >> Path: jsonte.exe
[+]: Failed to run sub process.
[+]: exit status 1
```

Project B file:
```json
{
  "$template": {
    "format_version": "1.10.0",
    "animation_controllers": {
      "{{#jsonteArray as iteration}}": {
        "controller.animation.templated_{{name}}.file": {
          "initial_state": "default",
          "states": {
            "default": {
              ...
            }
        ....
```

**Comment by stirante** [comment]
Issue solved through private conversation and was not related to either whisk or jsonte. The issue was that there were two files with the same name in module and in regolith project. Whisk doesn't merge files, so the array was missing.
