### ISSUE TITLE
Packer: Export can not be imported into MC

### ISSUE THREAD

**Issue by theaddonn** [MCDevKit/regolith-library#5]
Using the Packer filter to create `.mcpack`s comes with its problems, one of these problems being that Minecraft complains when attempting to import the final pack. The error is due to duplicate manifests at the same folder hierarchy, that's what MC at least says. I'm also just exporting a simple BP + RP, so switching the extension from `.mcpack` to `.mcaddon` actually fixed my issue

**Comment by stirante** [comment]
You can just set `output` setting so that the extension is `.mcaddon`

**Comment by theaddonn** [comment]
Thanks, that worked out!
